### ISSUE TITLE
ACCEPTING ₿ITCOIN DONATION

### ISSUE THREAD

**Issue by sonalder-darlene** [CreativityOpen/OpenCreativity#3]
What a great project, I really hope it will get some funding, contributions and usage !

I would like to donate but my only option is cryptocurrency. ₿itcoin is the ideal donation option for open source project for many reasons. I would personnaly donate using Monero if I had the choice because the privacy of the sender and reciever is better protected by default. You could also start accepting many other cryptocurrencies but I would personnaly focus on theses two only.

Open source projects often add donation addresses for other cryptocurrencies mainly :
- Ethereum ETH
- Litecoin LTC
- Dogecoin DOGE
- Tether USD USDT
- Circle USD USDC

If you don't want to deal with ₿itcoin or any of these payment methods then just close this issue :)

**Comment by scholablade** [comment]
Hey, thank you so much. ❤️
You are right in that cryptocurrency has many benefits (like privacy), I will push the QR code with the address to main soon, in the meantime, here is the address:
monero:445DuRRwp3HAMQEQ5RTTkBAGyid3v66PNBGtbArZh1VgMsrZhxi5dBWSK2HMeu1gtriRJkhPjAtmU3LEopUuAb4NUGSWgiT
P.S: I love Mr.Robot. :)
Thanks again.

**Comment by scholablade** [comment]
I added BTC and XMR as payment options, thank you for raising the issue.
